dist: xenial
language: python
python:
    - "3.7"
    - "3.7-dev"
    - "3.8-dev"
    - "nightly"

script:
  - coverage run --source=panda_core_data setup.py test

after_success:
  - coveralls

install:
    - pip install python-coveralls
    - python setup.py install
